name = "bharatlike-comments"
main = "index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "bharatlike-blog"
database_id = "2cff2e5e-9c90-4170-a2ab-de582b4544ba"
